hosts:
  ibm1:
    type: aix
    host: 10.62.36.3
    user: root
    pass: root
  hp23:
    type: hp-ux
    host: 10.62.36.23
    user: root
    pass: root
  hp22:
    type: hp-ux
    host: 10.62.36.22
    user: root
    pass: root
  hp21:
    type: hp-ux
    host: 10.62.36.21
    user: root
    pass: root
  bottom:
    type: brocade
    host: 10.32.32.199
    user: admin
    pass: password
  top:
    type: brocade
    host: 10.32.32.198
    user: admin
    pass: password
  swd77:
    type: brocade
    host: 10.32.32.195
    user: admin
    pass: password
  sym819:
    type: symmetrix
    host: 10.62.36.23
    user: root
    pass: root
    sid: 819
  sym056:
    type: symmetrix
    host: 10.62.36.23
    user: root
    pass: root
    sid: "056"